### ISSUE TITLE
USER STORY: Add contact page 

### ISSUE THREAD

**Issue by Julia-cloudname** [Julia-cloudname/marisol-2.0#7]
EPIC: #0 

As a **user**, I want to **see contact page**, so I can **contact owners**

**Tasks**

- [ ] Create contact page
- [ ] Add contact form and contact information
- [ ] Create email response functionality
